/** Constantes de dominio compartilhadas entre os tres clientes. */

export const APP_NAME = 'Ride';

export const OTP_LENGTH = 6;
export const OTP_TTL_SECONDS = 300;
export const OTP_MAX_ATTEMPTS = 5;
export const OTP_RESEND_COOLDOWN_SECONDS = 60;

export const RIDE_OFFER_TTL_SECONDS = 15;
export const RIDE_SEARCH_TIMEOUT_SECONDS = 120;
export const RIDE_ARRIVAL_RADIUS_METERS = 120;
export const RIDE_DEFAULT_SEARCH_RADIUS_KM = 3;
export const RIDE_MAX_SEARCH_RADIUS_KM = 15;
export const DRIVER_LOCATION_TTL_SECONDS = 120;

export const DEFAULT_PAGE_SIZE = 20;
export const MAX_PAGE_SIZE = 100;

export const EARTH_RADIUS_KM = 6371;

export const BRL = 'BRL';

/** Codigos de erro de negocio devolvidos pela API (campo `code`). */
export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  OTP_COOLDOWN: 'OTP_COOLDOWN',

  USER_BLOCKED: 'USER_BLOCKED',
  EMAIL_ALREADY_USED: 'EMAIL_ALREADY_USED',
  PHONE_ALREADY_USED: 'PHONE_ALREADY_USED',
  DRIVER_ALREADY_EXISTS: 'DRIVER_ALREADY_EXISTS',
  DRIVER_NOT_APPROVED: 'DRIVER_NOT_APPROVED',
  DOCUMENTS_INCOMPLETE: 'DOCUMENTS_INCOMPLETE',
  DOCUMENT_ALREADY_REVIEWED: 'DOCUMENT_ALREADY_REVIEWED',
  VEHICLE_PLATE_ALREADY_USED: 'VEHICLE_PLATE_ALREADY_USED',

  RIDE_NOT_FOUND: 'RIDE_NOT_FOUND',
  RIDE_INVALID_STATE: 'RIDE_INVALID_STATE',
  NO_DRIVER_AVAILABLE: 'NO_DRIVER_AVAILABLE',

  PAYMENT_FAILED: 'PAYMENT_FAILED',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  MIN_PAYOUT_NOT_REACHED: 'MIN_PAYOUT_NOT_REACHED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
